### ISSUE TITLE
Change Pod author to Yelp

### ISSUE THREAD

**Issue by SSheldon** [Yelp/yelp-ios#13]
We should get this published on cocoapods.org!

I'll need to get the right accounts configured first.

**Comment by d9chen** [comment]
@SSheldon  I actually followed https://guides.cocoapods.org/making/making-a-cocoapod.html to publish an initial version to cocoapods already.

**Comment by SSheldon** [comment]
Ah I see. Well I'd really like all of our pods to show up as published by Yelp. Currently this will say the author is "David Chen" and won't have any affiliation with Yelp.
