### ISSUE TITLE
Missing <YelpAPI/YLPClient.h> in Example Folder

### ISSUE THREAD

**Issue by dtnguy72** [Yelp/yelp-ios#44]
<img width="1280" alt="screen shot 2016-10-11 at 3 49 39 pm" src="https://cloud.githubusercontent.com/assets/21061299/19288166/5fd211ca-8fca-11e6-8e09-9216e8c4410f.png">

Hello,

I am missing the YelpClient file. Where can I get this file? I tried installing these pods "YelpAPI" &
pod "YelpAPISwift" but it didn't resolve the issue.

**Comment by SSheldon** [comment]
Hey, it looks like maybe you've opened `Example/YelpAPI.xcodeproj` instead of `YelpAPI.xcworkspace`. Can you open the workspace instead and see if that resolves your issue? The workspace needs to be used so that it can find the CocoaPods.

**Comment by dtnguy72** [comment]
I just reinstalled the pod. 
Analyzing dependencies
Downloading dependencies
Using OCMock (3.1.5)
Using OHHTTPStubs (4.6.0)
Using OMGHTTPURLRQ (3.1.1)
Using TDOAuth (1.1.2)
Generating Pods project
Integrating client project

This time when I opened the workspace I got this issue.
<img width="1280" alt="screen shot 2016-10-11 at 7 56 59 pm" src="https://cloud.githubusercontent.com/assets/21061299/19293838/5a7ecfc4-8fed-11e6-8331-461dc4ade0e6.png">

**Comment by SSheldon** [comment]
Which version of cocoapods are you using? I am seeing issues when using newer versions of cocoapods, but haven't been able to repro this exact issue.

**Comment by dtnguy72** [comment]
I am using pod “YelpAPI” for the Example folder. When I do a pod install for the Yelp-ios master folder it installs. 
Analyzing dependencies
Downloading dependencies
Using OCMock (3.1.5)
Using OHHTTPStubs (4.6.0)
Using OMGHTTPURLRQ (3.1.1)
Using TDOAuth (1.1.2)
Generating Pods project
Integrating client project

**Comment by SSheldon** [comment]
Hey @dtnguy72, the version of CocoaPods we were using was a little out of date. I've updated it and cleaned up the project a bit in #45. Once that gets merged, I'll ask ya to try this again and maybe that will resolve your issue!

**Comment by dtnguy72** [comment]
Thanks so much! I really appreciate this.

**Comment by SSheldon** [comment]
Hey @dtnguy72, the project changes are in master! Could you pull master, pod install again, and give it a try? I'm not certain that it'll fix the issue you were experiencing, so let me know if you get any new error output.

**Comment by dtnguy72** [comment]
Did you want me to do a pod install on the entire project folder or just the example folder? Because there is no Xcode project that exists in the example folder to do a pod install on.

**Comment by SSheldon** [comment]
Yep, pod install for the entire project folder! The example app was moved into the same project as the library, so they're all in the same project now.

**Comment by dtnguy72** [comment]
I just did deleted the workspace file found in the project and did a pod install that created a new workspace file. My terminal displayed:
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.1.0.rc.3) is higher than the version of the current executable (1.0.1). Incompatibility issues may arise.
Downloading dependencies
Installing OCMock (3.1.5)
Installing OHHTTPStubs (4.6.0)
Installing OMGHTTPURLRQ (3.1.1)
Installing TDOAuth (1.1.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `YelpAPI.xcworkspace` for this project from now on.

<img width="1280" alt="screen shot 2016-10-18 at 2 32 31 pm" src="https://cloud.githubusercontent.com/assets/21061299/19493329/cea25a90-953f-11e6-8e8a-0f15259ed571.png">

When I opened the newly created workspace I got this.

**Comment by SSheldon** [comment]
@dtnguy72, you shouldn't have to delete the existing workspace!

How about:
1. Make a fresh clone of this repo
2. Run `pod install` (without deleting the workspace or changing anything)
3. Then `open YelpAPI.xcworkspace` and try to build

Then see if that works.

**Comment by dtnguy72** [comment]
I just found your steps and build the project with the pod "YelpAPI" installed. The project built without any errors in the xcworkspace.

**Comment by dtnguy72** [comment]
*followed

**Comment by dtnguy72** [comment]
Thank you!

**Comment by SSheldon** [comment]
No problem, glad it's working for you now!
