### ISSUE TITLE
Address array may include NSNull, violating type annotations

### ISSUE THREAD

**Issue by SSheldon** [Yelp/yelp-ios#52]
For example, if you lookup Philz Coffee the address array looks like: `["549 Castro St", <null>, ""]`. I'm unclear on why there's a distinction between a null value and an empty string.

I feel like this will be an issue in more places. I did handle it for `YLPUser.imageURL`. In general, on APIv3 it looks like now we need to audit for nullability.

**Comment by SSheldon** [comment]
@tomelm, I saw you working on something nullability related recently, is there an easy way to see a list of which properties may be null in the API v3 responses?

**Comment by tomelm** [comment]
Oh yea, this is definitely because of today's push. Right now, the 5 fields that can be nullable are latitude, longitude, address1, address2, and address3.

**Comment by SSheldon** [comment]
Any others outside of the Business object? I found that the `image_url` of User objects can also be null.

Thanks @tomelm!

**Comment by tomelm** [comment]
Hmm, the 5 I listed were the only ones I explicitly changed to support null values internally. Let me see if I can git grep that for you

**Comment by tomelm** [comment]
@SSheldon Oh heh, yea the only other field that's set to nullable is the user photo id for reviews.
