### ISSUE TITLE
Unable to find a specification for `YelpAPI` when I try to install the pod

### ISSUE THREAD

**Issue by Hsanka6** [Yelp/yelp-ios#62]
Is the pod deprecated?

**Comment by mittonk** [comment]
@Hsanka6 : Not deprecated --- I have a hunch this might be fallout from our yelp-ios 2.0.0 release.

What's the full error message text?  Are you specifying a version number when installing YelpAPI?

**Comment by Hsanka6** [comment]
the full message is: " Unable to find a specification for `YelpAPI` " and which one should I specify it to?

**Comment by mittonk** [comment]
@d9chen , @SSheldon : Thoughts?

**Comment by SSheldon** [comment]
@Hsanka6, have you run `pod repo update` before trying to install? Could you paste the results of `pod env` here for us to help debug?

**Comment by Hsanka6** [comment]
Yes I have and I have still got errors and I will next week when I'm done with my finals

**Comment by SSheldon** [comment]
Sounds good @Hsanka6, I'll take a look once you have time to provide that information. Good luck on your finals 😊

**Comment by Hsanka6** [comment]
I think I had an issue with my other project because I just tried using a different branch and adding the pod and it worked

**Comment by Hsanka6** [comment]
Is there any examples of how to use the api in swift btw?

**Comment by SSheldon** [comment]
We're working on adding more Swift examples, for now the closest thing is [one of the tests is written in Swift](https://github.com/Yelp/yelp-ios/blob/2.0.0/YelpAPITests/Client/YLPReviewsClientTestCase.swift#L27).

Glad everything's working now!
