### ISSUE TITLE
Businesses found; however, some locations are nil.

### ISSUE THREAD

**Issue by e-jam** [Yelp/yelp-ios#71]
I ran into a recent problem that did not exist a few days ago. When I make an API call, it does go through successfully and I do get a list of business; however, some "locations" / "coordinates" belonging to a few businesses are nil and it is causing my code to break. I am confused as to how is it possible to find a business without location / coordinate info. As I already mentioned this did not happen before. I would really appreciate if someone could point out as to why this is happening?

**Comment by virgytam** [comment]
Hi @e-jam! Can you include an example response with nil fields?

**Comment by mittonk** [comment]
Let's centralize all the debugging in #266!

**Comment by e-jam** [comment]
@virgytam There are some example provided on issue #266. I will also post my own example response. https://github.com/Yelp/yelp-fusion/issues/266
