### ISSUE TITLE
Yelp Fusion switch to API KEYS

### ISSUE THREAD

**Issue by Linger-Software** [Yelp/yelp-ios#73]
"Prior to December 7, 2017 the API used OAuth 2.0 to authenticate requests to the API. In an effort to simplify authentication, starting March 1, 2018 the API will no longer use OAuth 2.0 for requests and will move over to only API Keys. The token endpoint will be deprecated March 1, 2018, at which point you will no longer be able to make requests to it. "
-source: Yelp (https://www.yelp.com/developers/documentation/v3/authentication#where-is-my-client-secret-going) 

Is there an update to support this in the roadmap? We're closing in on less than a month with no announced update for the yelp-ios project.

**Comment by SSheldon** [comment]
I've put an update together in #74.

**Comment by Linger-Software** [comment]
Thanks for the quick update and response! I can't wait to look into and apply the new commits!

**Comment by Linger-Software** [comment]
I'll leave this issue open until after the March switch happens so people get pointed to 74
